const users = [
    {
      user_id: 1,
      user_name: "Aarav Sharma",
      user_about: "A software developer with a passion for coding and technology.",
      user_address: {
        street: "MG Road",
        city: "Mumbai",
        state: "Maharashtra",
        zipcode: "400001",
        country: "India",
      },
      user_email: "aarav.sharma@example.com",
      user_pic: "https://example.com/pic/aarav.jpg",
    },
    {
      user_id: 2,
      user_name: "Priya Patel",
      user_about: "Digital marketing expert and content strategist.",
      user_address: {
        street: "Vashi",
        city: "Navi Mumbai",
        state: "Maharashtra",
        zipcode: "400703",
        country: "India",
      },
      user_email: "priya.patel@example.com",
      user_pic: "https://example.com/pic/priya.jpg",
    },
    {
      user_id: 3,
      user_name: "Rohan Gupta",
      user_about: "Data scientist with a love for solving complex problems.",
      user_address: {
        street: "Bengaluru Road",
        city: "Bengaluru",
        state: "Karnataka",
        zipcode: "560001",
        country: "India",
      },
      user_email: "rohan.gupta@example.com",
      user_pic: "https://example.com/pic/rohan.jpg",
    },
    {
      user_id: 4,
      user_name: "Anjali Reddy",
      user_about: "A passionate graphic designer with an eye for detail.",
      user_address: {
        street: "Jubilee Hills",
        city: "Hyderabad",
        state: "Telangana",
        zipcode: "500033",
        country: "India",
      },
      user_email: "anjali.reddy@example.com",
      user_pic: "https://example.com/pic/anjali.jpg",
    },
    {
      user_id: 5,
      user_name: "Aakash Verma",
      user_about: "Mechanical engineer with an interest in robotics.",
      user_address: {
        street: "Nehru Place",
        city: "Delhi",
        state: "Delhi",
        zipcode: "110019",
        country: "India",
      },
      user_email: "aakash.verma@example.com",
      user_pic: "https://example.com/pic/aakash.jpg",
    },
    {
      user_id: 6,
      user_name: "Sneha Iyer",
      user_about: "Marketing manager and advocate for women empowerment.",
      user_address: {
        street: "Thane West",
        city: "Mumbai",
        state: "Maharashtra",
        zipcode: "400601",
        country: "India",
      },
      user_email: "sneha.iyer@example.com",
      user_pic: "https://example.com/pic/sneha.jpg",
    },
    {
      user_id: 7,
      user_name: "Vikram Singh",
      user_about: "Financial consultant helping businesses grow through effective strategies.",
      user_address: {
        street: "Park Street",
        city: "Kolkata",
        state: "West Bengal",
        zipcode: "700016",
        country: "India",
      },
      user_email: "vikram.singh@example.com",
      user_pic: "https://example.com/pic/vikram.jpg",
    },
    {
      user_id: 8,
      user_name: "Meera Bansal",
      user_about: "Entrepreneur building innovative tech solutions.",
      user_address: {
        street: "Koramangala",
        city: "Bengaluru",
        state: "Karnataka",
        zipcode: "560034",
        country: "India",
      },
      user_email: "meera.bansal@example.com",
      user_pic: "https://example.com/pic/meera.jpg",
    },
    {
      user_id: 9,
      user_name: "Kunal Desai",
      user_about: "UX/UI designer with a focus on user-centric design.",
      user_address: {
        street: "Andheri West",
        city: "Mumbai",
        state: "Maharashtra",
        zipcode: "400053",
        country: "India",
      },
      user_email: "kunal.desai@example.com",
      user_pic: "https://example.com/pic/kunal.jpg",
    },
    {
      user_id: 10,
      user_name: "Tanvi Joshi",
      user_about: "A content creator exploring new avenues in social media.",
      user_address: {
        street: "Indiranagar",
        city: "Bengaluru",
        state: "Karnataka",
        zipcode: "560038",
        country: "India",
      },
      user_email: "tanvi.joshi@example.com",
      user_pic: "https://example.com/pic/tanvi.jpg",
    },
  ];
  export default users